### ISSUE TITLE
Please explain the arguments to “skglControl.Invalidate();”

### ISSUE THREAD

**Issue by CBrauer** [swharden/Maui.Graphics#2]
Hello,

I’m converting my Maui Graphics to .NET 7, and I’m wondering about the difference between:

 ```
     skglControl.Invalidate();
     skglControl.Update();
```

and 
`      skglControl.Invalidate(true);`

I want to completely redraw my entire drawing.  Which one should I do?

Charles

**Comment by swharden** [comment]
Hi @CBrauer,

I'm just a guy who registered https://maui.graphics because it kept giving a no response HTTP error and I wanted to put something more useful there. This repository is the content of that website.

I think this question should be directed to the Maui.Graphics GitHub repository: https://github.com/dotnet/Microsoft.Maui.Graphics/issues

Good luck!

**Comment by swharden** [comment]
PS: I think the difference is `Invalidate()` means "next time the screen redraws, redraw this component", whereas `Update()` means "stop what you're doing now and force a redraw this instant"

**Comment by swharden** [comment]
Actually this isn't even a Maui.Graphics question, it's a SkiaSharp question, and actually it's a Windows Forms question

* https://stackoverflow.com/questions/2286613/invalidate-vs-update
* https://itecnote.com/tecnote/c-invalidate-vs-update/
* https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.invalidate

Hope it helps! 🚀
